apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:3.1.0.Final
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: POSTGRES_DATABASE
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name:  PROXY_ADDRESS_FORWARDING
          value: "true"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: keycloak
  name: keycloak
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
  selector:
    name: keycloak
